GCP_KEYFILE_PATH = "river-treat-468823-m3-5c1dace0df38.json"
BQ_TABLE = "dataset_AIS_2024_silver_refined.table_AIS_2024_silver_refined"

BQ_PROJECT = "river-treat-468823-m3"                       # para calificar nombres
BQ_MODEL_DATASET = "dataset_AIS_2024_silver_refined"    # donde vivirán los MODELOS
BQ_RESULTS_TABLE = "dataset_AIS_2024_silver_refined.anomaly_results"  # (opcional) tabla de resultados
